#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikasiToko_Gamiat
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbAppToko")]
	public partial class KaryawanClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkaryawan(karyawan instance);
    partial void Updatekaryawan(karyawan instance);
    partial void Deletekaryawan(karyawan instance);
    #endregion
		
		public KaryawanClassesDataContext() : 
				base(global::AplikasiToko_Gamiat.Properties.Settings.Default.DbAppTokoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KaryawanClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KaryawanClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KaryawanClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KaryawanClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<karyawan> karyawans
		{
			get
			{
				return this.GetTable<karyawan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.karyawan")]
	public partial class karyawan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nik;
		
		private string _nama;
		
		private string _alamat;
		
		private string _kota;
		
		private string _tempat_lahir;
		
		private System.DateTime _tgl_lahir;
		
		private string _agama;
		
		private char _jk;
		
		private string _status_menikah;
		
		private int _tanggungan;
		
		private string _pendidikan;
		
		private int _no_telp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnikChanging(string value);
    partial void OnnikChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnkotaChanging(string value);
    partial void OnkotaChanged();
    partial void Ontempat_lahirChanging(string value);
    partial void Ontempat_lahirChanged();
    partial void Ontgl_lahirChanging(System.DateTime value);
    partial void Ontgl_lahirChanged();
    partial void OnagamaChanging(string value);
    partial void OnagamaChanged();
    partial void OnjkChanging(char value);
    partial void OnjkChanged();
    partial void Onstatus_menikahChanging(string value);
    partial void Onstatus_menikahChanged();
    partial void OntanggunganChanging(int value);
    partial void OntanggunganChanged();
    partial void OnpendidikanChanging(string value);
    partial void OnpendidikanChanged();
    partial void Onno_telpChanging(int value);
    partial void Onno_telpChanged();
    #endregion
		
		public karyawan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nik", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nik
		{
			get
			{
				return this._nik;
			}
			set
			{
				if ((this._nik != value))
				{
					this.OnnikChanging(value);
					this.SendPropertyChanging();
					this._nik = value;
					this.SendPropertyChanged("nik");
					this.OnnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this.OnkotaChanging(value);
					this.SendPropertyChanging();
					this._kota = value;
					this.SendPropertyChanged("kota");
					this.OnkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tempat_lahir", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string tempat_lahir
		{
			get
			{
				return this._tempat_lahir;
			}
			set
			{
				if ((this._tempat_lahir != value))
				{
					this.Ontempat_lahirChanging(value);
					this.SendPropertyChanging();
					this._tempat_lahir = value;
					this.SendPropertyChanged("tempat_lahir");
					this.Ontempat_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_lahir", DbType="DateTime NOT NULL")]
		public System.DateTime tgl_lahir
		{
			get
			{
				return this._tgl_lahir;
			}
			set
			{
				if ((this._tgl_lahir != value))
				{
					this.Ontgl_lahirChanging(value);
					this.SendPropertyChanging();
					this._tgl_lahir = value;
					this.SendPropertyChanged("tgl_lahir");
					this.Ontgl_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agama", DbType="VarChar(10)")]
		public string agama
		{
			get
			{
				return this._agama;
			}
			set
			{
				if ((this._agama != value))
				{
					this.OnagamaChanging(value);
					this.SendPropertyChanging();
					this._agama = value;
					this.SendPropertyChanged("agama");
					this.OnagamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jk", DbType="Char(1) NOT NULL")]
		public char jk
		{
			get
			{
				return this._jk;
			}
			set
			{
				if ((this._jk != value))
				{
					this.OnjkChanging(value);
					this.SendPropertyChanging();
					this._jk = value;
					this.SendPropertyChanged("jk");
					this.OnjkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_menikah", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status_menikah
		{
			get
			{
				return this._status_menikah;
			}
			set
			{
				if ((this._status_menikah != value))
				{
					this.Onstatus_menikahChanging(value);
					this.SendPropertyChanging();
					this._status_menikah = value;
					this.SendPropertyChanged("status_menikah");
					this.Onstatus_menikahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggungan", DbType="Int NOT NULL")]
		public int tanggungan
		{
			get
			{
				return this._tanggungan;
			}
			set
			{
				if ((this._tanggungan != value))
				{
					this.OntanggunganChanging(value);
					this.SendPropertyChanging();
					this._tanggungan = value;
					this.SendPropertyChanged("tanggungan");
					this.OntanggunganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pendidikan", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string pendidikan
		{
			get
			{
				return this._pendidikan;
			}
			set
			{
				if ((this._pendidikan != value))
				{
					this.OnpendidikanChanging(value);
					this.SendPropertyChanging();
					this._pendidikan = value;
					this.SendPropertyChanged("pendidikan");
					this.OnpendidikanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_telp", DbType="Int NOT NULL")]
		public int no_telp
		{
			get
			{
				return this._no_telp;
			}
			set
			{
				if ((this._no_telp != value))
				{
					this.Onno_telpChanging(value);
					this.SendPropertyChanging();
					this._no_telp = value;
					this.SendPropertyChanged("no_telp");
					this.Onno_telpChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
