#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikasiToko_Gamiat
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbAppToko")]
	public partial class ProdukClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbarang(barang instance);
    partial void Updatebarang(barang instance);
    partial void Deletebarang(barang instance);
    #endregion
		
		public ProdukClassesDataContext() : 
				base(global::AplikasiToko_Gamiat.Properties.Settings.Default.DbAppTokoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProdukClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdukClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdukClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdukClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<barang> barangs
		{
			get
			{
				return this.GetTable<barang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.barang")]
	public partial class barang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _kode_brg;
		
		private string _nama_brg;
		
		private int _diskon;
		
		private decimal _harga_jual;
		
		private int _stok_gudang;
		
		private int _stok_rak;
		
		private int _rusak;
		
		private string _satuan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_brgChanging(string value);
    partial void Onkode_brgChanged();
    partial void Onnama_brgChanging(string value);
    partial void Onnama_brgChanged();
    partial void OndiskonChanging(int value);
    partial void OndiskonChanged();
    partial void Onharga_jualChanging(decimal value);
    partial void Onharga_jualChanged();
    partial void Onstok_gudangChanging(int value);
    partial void Onstok_gudangChanged();
    partial void Onstok_rakChanging(int value);
    partial void Onstok_rakChanged();
    partial void OnrusakChanging(int value);
    partial void OnrusakChanged();
    partial void OnsatuanChanging(string value);
    partial void OnsatuanChanged();
    #endregion
		
		public barang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_brg", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string kode_brg
		{
			get
			{
				return this._kode_brg;
			}
			set
			{
				if ((this._kode_brg != value))
				{
					this.Onkode_brgChanging(value);
					this.SendPropertyChanging();
					this._kode_brg = value;
					this.SendPropertyChanged("kode_brg");
					this.Onkode_brgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_brg", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama_brg
		{
			get
			{
				return this._nama_brg;
			}
			set
			{
				if ((this._nama_brg != value))
				{
					this.Onnama_brgChanging(value);
					this.SendPropertyChanging();
					this._nama_brg = value;
					this.SendPropertyChanged("nama_brg");
					this.Onnama_brgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diskon", DbType="Int NOT NULL")]
		public int diskon
		{
			get
			{
				return this._diskon;
			}
			set
			{
				if ((this._diskon != value))
				{
					this.OndiskonChanging(value);
					this.SendPropertyChanging();
					this._diskon = value;
					this.SendPropertyChanged("diskon");
					this.OndiskonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga_jual", DbType="Money NOT NULL")]
		public decimal harga_jual
		{
			get
			{
				return this._harga_jual;
			}
			set
			{
				if ((this._harga_jual != value))
				{
					this.Onharga_jualChanging(value);
					this.SendPropertyChanging();
					this._harga_jual = value;
					this.SendPropertyChanged("harga_jual");
					this.Onharga_jualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stok_gudang", DbType="Int NOT NULL")]
		public int stok_gudang
		{
			get
			{
				return this._stok_gudang;
			}
			set
			{
				if ((this._stok_gudang != value))
				{
					this.Onstok_gudangChanging(value);
					this.SendPropertyChanging();
					this._stok_gudang = value;
					this.SendPropertyChanged("stok_gudang");
					this.Onstok_gudangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stok_rak", DbType="Int NOT NULL")]
		public int stok_rak
		{
			get
			{
				return this._stok_rak;
			}
			set
			{
				if ((this._stok_rak != value))
				{
					this.Onstok_rakChanging(value);
					this.SendPropertyChanging();
					this._stok_rak = value;
					this.SendPropertyChanged("stok_rak");
					this.Onstok_rakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rusak", DbType="Int NOT NULL")]
		public int rusak
		{
			get
			{
				return this._rusak;
			}
			set
			{
				if ((this._rusak != value))
				{
					this.OnrusakChanging(value);
					this.SendPropertyChanging();
					this._rusak = value;
					this.SendPropertyChanged("rusak");
					this.OnrusakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satuan", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string satuan
		{
			get
			{
				return this._satuan;
			}
			set
			{
				if ((this._satuan != value))
				{
					this.OnsatuanChanging(value);
					this.SendPropertyChanging();
					this._satuan = value;
					this.SendPropertyChanged("satuan");
					this.OnsatuanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
